prometheus:
  prometheusSpec:
    # listenLocal: true
    web:
      tlsConfig:
        clientAuthType: NoClientCert
        keySecret:
          key: tls.key
          name: prometheus-tls-secret
        cert:
          secret:
            key: tls.crt
            name: prometheus-tls-secret
    # service:
    #   # port: 443
    #   # targetPort: 443
    #   port: 9090
    #   targetPort: 9090
    # serviceMonitor:
    #   scheme: https
    #   tlsConfig:
    #     insecureSkipVerify: true
    alertingEndpoints:
    - name: v4m-alertmanager 
      namespace: monitoring
      port: http-web
      scheme: https
      tlsConfig:
        insecureSkipVerify: true

alertmanager:
  alertmanagerSpec:
    # listenLocal: true
    web:
      tlsConfig:
        clientAuthType: NoClientCert
        keySecret:
          key: tls.key
          name: alertmanager-tls-secret
        cert:
          secret:
            key: tls.crt
            name: alertmanager-tls-secret
    # service:
    #   port: 9093
    #   targetPort: 9093
    # serviceMonitor:
    #   scheme: https
    #   tlsConfig:
    #     insecureSkipVerify: true

prometheus-node-exporter:
  extraArgs:
  - '--web.config.file=/opt/node-exporter/node-exporter-web.yaml'
  configmaps:
  - name: node-exporter-tls-web-config
    mountPath: /opt/node-exporter

# node-exporter helm chart does not yet support HTTPS
# node-exporter:
#   sidecarVolumeMount:
#   - name: tls-secret
#     mountPath: /cert
#     readOnly: true

grafana:
  readinessProbe:
    httpGet:
      scheme: HTTPS
      port: 3001
  livenessProbe:
    httpGet:
      scheme: HTTPS
      port: 3001

  service:
    port: 31100
    targetPort: 3001

  extraSecretMounts:
  - name: grafana-tls
    mountPath: /cert
    secretName: grafana-tls-secret
    readOnly: true
    subPath: ""

  "grafana.ini":
    server:
      protocol: https
      http_port: 3001
      cert_file: /cert/tls.crt
      cert_key: /cert/tls.key

  sidecar:
    datasources:
      defaultDatasourceEnabled: false
      # - name: Prometheus
      #   type: prometheus
      #   access: proxy
      #   isDefault: true
      # jsonData:
      #   tlsSkipVerify: true
      # editable: true
      # url: https://v4m-prometheus.monitoring:9090
