prometheus:
  prometheusSpec:
    web:
      tlsConfig:
        clientAuthType: NoClientCert
        keySecret:
          key: tls.key
          name: prometheus-tls-secret
        cert:
          secret:
            key: tls.crt
            name: prometheus-tls-secret
    service:
      port: 9090
      targetPort: 9090
    serviceMonitor:
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
    alertingEndpoints:
    - name: v4m-alertmanager 
      namespace: monitoring
      port: http-web
      scheme: https
      tlsConfig:
        insecureSkipVerify: true

alertmanager:
  alertmanagerSpec:
    web:
      tlsConfig:
        clientAuthType: NoClientCert
        keySecret:
          key: tls.key
          name: alertmanager-tls-secret
        cert:
          secret:
            key: tls.crt
            name: alertmanager-tls-secret
    service:
      port: 9093
      targetPort: 9093
    serviceMonitor:
      scheme: https
      tlsConfig:
        insecureSkipVerify: true

grafana:
  readinessProbe:
    httpGet:
      scheme: HTTPS
      port: 3000
  livenessProbe:
    httpGet:
      scheme: HTTPS
      port: 3000
  extraSecretMounts:
  - name: grafana-tls
    mountPath: /cert
    secretName: grafana-tls-secret
    readOnly: true
    subPath: ""
  service:
    port: 3000
    targetPort: 3000
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
  "grafana.ini":
    server:
      protocol: https
      cert_file: /cert/tls.crt
      cert_key: /cert/tls.key
