prometheus:
  prometheusSpec:
    web:
      tlsConfig:
        keySecret:
          key: tls.key
          name: prometheus-tls-secret
        cert:
          secret:
            key: tls.crt
            name: prometheus-tls-secret

alertmanager:
  alertmanagerSpec:
    web:
      tlsConfig:
        keySecret:
          key: tls.key
          name: alertmanager-tls-secret
        cert:
          secret:
            key: tls.crt
            name: alertmanager-tls-secret

prometheus-node-exporter:
  extraArgs:
  - '--web.config.file=/opt/node-exporter/node-exporter-web.yaml'
  configmaps:
  - name: node-exporter-tls-web-config
    mountPath: /opt/node-exporter

# node-exporter helm chart does not yet support HTTPS
# node-exporter:
#   sidecarVolumeMount:
#   - name: tls-secret
#     mountPath: /cert
#     readOnly: true

grafana:
  readinessProbe:
    httpGet:
      scheme: HTTPS
      port: 3001
  livenessProbe:
    httpGet:
      scheme: HTTPS
      port: 3001

  service:
    port: 31100
    targetPort: 3001

  extraSecretMounts:
  - name: grafana-tls
    mountPath: /cert
    secretName: grafana-tls-secret
    readOnly: true
    subPath: ""

  "grafana.ini":
    server:
      protocol: https
      http_port: 3001
      cert_file: /cert/tls.crt
      cert_key: /cert/tls.key
